AWSTemplateFormatVersion: '2010-09-09'
Description: setup

Parameters:
  NamePrefix:
    Type: String
  ArtifactBucketName:
    Type: String

Resources:
  ArtifactBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref ArtifactBucketName
      AccessControl: Private
